export const TEXTS_DE = {
  title: 'ArmikTech',
  tagline: 'Gebrauchte PC-Hardware & Komponenten',
  heroSubtitle: 'GPUs, CPUs, RAM und komplette Builds — geprüft, fair bepreist, direkt anfragen.',
  sale: 'Sale',
  all: 'Alle',
  category: 'Kategorie',
  subCategory: 'Unterkategorie',
  price: 'Preis',
  minPrice: 'Min €',
  maxPrice: 'Max €',
  search: 'Suchen…',
  searchHero: 'Was suchst du? RTX 4070, Ryzen, RAM…',
  noItems: 'Keine Artikel gefunden.',
  priceOnRequest: 'Preis auf Anfrage',
  loading: 'Katalog wird geladen…',
  noCatalog: 'Noch keine Artikel bei ArmikTech.',
  contact: 'Anfrage senden',
  aboutItem: 'Anfrage zu diesem Artikel',
  yourName: 'Ihr Name',
  yourEmail: 'E-Mail',
  yourPhone: 'Telefon',
  yourMessage: 'Nachricht',
  send: 'Senden',
  sent: 'Nachricht gesendet.',
  sendError: 'Fehler beim Senden.',
  close: 'Schließen',
  specs: 'Technische Daten',
  onSale: 'Angebot',
  sort: 'Sortieren',
  toHome: 'Zur Startseite',
  priceLow: 'Preis aufsteigend',
  priceHigh: 'Preis absteigend',
  nameAz: 'Name A–Z',
  results: 'Ergebnisse',
  viewDetails: 'Details anzeigen',
  readDescription: 'Beschreibung lesen',
  backToTop: 'Nach oben',
  keyFeatures: 'Was ist drin?',
  keySpecs: 'Eigenschaften',
  aboutUs: 'Über uns',
  contactLink: 'Kontakt',
  imprint: 'Impressum',
  privacy: 'Datenschutz',
  terms: 'AGB',
  legal: 'Alle Rechte vorbehalten. Alle genannten Marken gehören den jeweiligen Rechteinhabern.',
  wishlist: 'Merkliste',
  addToWishlist: 'Zur Merkliste',
  removeFromWishlist: 'Aus Merkliste',
  share: 'Teilen',
  similarItems: 'Ähnliche Artikel',
  recentlyViewed: 'Zuletzt angesehen',
  home: 'Start',
  badgeNew: 'Neu',
  badgePriceReduced: 'Preis reduziert',
  onlyOneLeft: 'Nur noch 1',
  outOfStock: 'Ausverkauft',
  langDe: 'DE',
  langEn: 'EN',
  filters: 'Filter',
  clearFilters: 'Zurücksetzen',
  shopNow: 'Angebote entdecken',
  itemsAvailable: 'Artikel verfügbar',
  resetHint: 'Filter anpassen oder Alle / Sale wechseln.',
  emptyTitle: 'Noch keine Artikel',
  heroCta: 'Zu den Angeboten',
  heroCtaSale: 'Sale entdecken',
  categoriesHeading: 'Nach Kategorie stöbern',
  categoriesSub: 'Jede Kategorie, ein Klick entfernt.',
  itemsCount: 'Artikel',
  dealTag: 'Bestes Angebot',
  dealCtaContact: 'Anfrage senden',
  dealCtaDetails: 'Details ansehen',
  stockOne: 'Nur noch 1 Stück',
  stockFew: 'Nur noch {n} Stück',
  stockAvailable: 'Verfügbar',
  bestsellersHeading: 'Bestseller der Woche',
  bestsellersSub: 'Direkt aus unserem geprüften Lager.',
  adTag: 'Premium Empfehlung',
  adCta: 'Jetzt anfragen',
  adNote: 'Individuell konfigurierbar auf Anfrage.',
  trustCheckedTitle: 'Geprüfte Hardware',
  trustCheckedDesc: 'Jeder Artikel wird vor dem Verkauf kontrolliert.',
  trustDirectTitle: 'Direkte Anfrage',
  trustDirectDesc: 'Formular ausfüllen, wir melden uns persönlich.',
  trustFairTitle: 'Faire Preise',
  trustFairDesc: 'Marktorientiert kalkuliert, ohne Aufschläge.',
  trustSupportTitle: 'Persönlicher Support',
  trustSupportDesc: 'Fragen zu Kompatibilität? Wir helfen weiter.',
};

export const TEXTS_EN = {
  title: 'ArmikTech',
  tagline: 'Used PC hardware & components',
  heroSubtitle: 'GPUs, CPUs, RAM and complete builds — inspected, fairly priced, inquire directly.',
  sale: 'Sale',
  all: 'All',
  category: 'Category',
  subCategory: 'Subcategory',
  price: 'Price',
  minPrice: 'Min €',
  maxPrice: 'Max €',
  search: 'Search…',
  searchHero: 'What are you looking for? RTX 4070, Ryzen, RAM…',
  noItems: 'No items found.',
  priceOnRequest: 'Price on request',
  loading: 'Loading catalog…',
  noCatalog: 'No items at ArmikTech yet.',
  contact: 'Contact',
  aboutItem: 'Inquiry about this item',
  yourName: 'Your name',
  yourEmail: 'Email',
  yourPhone: 'Phone',
  yourMessage: 'Message',
  send: 'Send',
  sent: 'Message sent.',
  sendError: 'Error sending.',
  close: 'Close',
  specs: 'Specifications',
  onSale: 'Sale',
  sort: 'Sort',
  toHome: 'Home',
  priceLow: 'Price ascending',
  priceHigh: 'Price descending',
  nameAz: 'Name A–Z',
  results: 'Results',
  viewDetails: 'View details',
  readDescription: 'Read description',
  backToTop: 'Back to top',
  keyFeatures: "What's inside?",
  keySpecs: 'Features',
  aboutUs: 'About us',
  contactLink: 'Contact',
  imprint: 'Imprint',
  privacy: 'Privacy',
  terms: 'Terms',
  legal: 'All rights reserved. All trademarks belong to their respective owners.',
  wishlist: 'Wishlist',
  addToWishlist: 'Add to wishlist',
  removeFromWishlist: 'Remove from wishlist',
  share: 'Share',
  similarItems: 'Similar items',
  recentlyViewed: 'Recently viewed',
  home: 'Home',
  badgeNew: 'New',
  badgePriceReduced: 'Price reduced',
  onlyOneLeft: 'Only 1 left',
  outOfStock: 'Out of stock',
  langDe: 'DE',
  langEn: 'EN',
  filters: 'Filters',
  clearFilters: 'Clear all',
  shopNow: 'Browse deals',
  itemsAvailable: 'items available',
  resetHint: 'Adjust filters or switch All / Sale.',
  emptyTitle: 'No items yet',
  heroCta: 'Shop the store',
  heroCtaSale: 'See sale items',
  categoriesHeading: 'Shop by category',
  categoriesSub: 'Every category, one click away.',
  itemsCount: 'items',
  dealTag: 'Best deal',
  dealCtaContact: 'Send inquiry',
  dealCtaDetails: 'View details',
  stockOne: 'Only 1 left',
  stockFew: 'Only {n} left',
  stockAvailable: 'Available',
  bestsellersHeading: 'Best sellers this week',
  bestsellersSub: 'Straight from our inspected stock.',
  adTag: 'Featured build',
  adCta: 'Inquire now',
  adNote: 'Custom-configured on request.',
  trustCheckedTitle: 'Inspected hardware',
  trustCheckedDesc: 'Every item is checked before it goes up for sale.',
  trustDirectTitle: 'Direct inquiry',
  trustDirectDesc: 'Fill out the form and we get back to you personally.',
  trustFairTitle: 'Fair pricing',
  trustFairDesc: 'Priced against the market, no hidden markups.',
  trustSupportTitle: 'Personal support',
  trustSupportDesc: 'Questions about compatibility? We can help.',
};

export type StorefrontTexts = typeof TEXTS_DE;

export function getItemDescription(
  item: { storeDescription?: string; storeDescriptionEn?: string },
  lang: 'de' | 'en'
): string | undefined {
  if (lang === 'en' && item.storeDescriptionEn) return item.storeDescriptionEn;
  return item.storeDescription;
}
